export interface Venue {
  slug: string;
  name: string;
  nameEn: string;
  tagline: string;
  taglineEn: string;
  tag: 'hot' | 'new' | 'value' | 'premium' | 'KTV';
  price: number;
  currency: string;
  area: string;
  areaEn: string;
  rating: number;
  image: string;
  gallery?: string[];
  galleryCaptions?: string[];
  videos?: string[];
  features: string[];
  featuresEn: string[];
  highlights: { icon: string; title: string; titleEn: string; desc: string; descEn: string }[];
  reviewSections: { title: string; titleEn: string; content: string; contentEn: string }[];
  pricing: { name: string; nameEn: string; price: number; desc: string; descEn: string }[];
  pros: string[];
  prosEn: string[];
  cons: string[];
  consEn: string[];
  suitableFor: string;
  suitableForEn: string;
  ranking?: number;
  longDescription?: string;
  longDescriptionEn?: string;
  coverBadge?: string;
  coverBadgeEn?: string;
  coverImage?: string;
  suspended?: boolean;
  categories?: string[];
  aliases?: string;
  aliasesEn?: string;
  technicianCount?: string;
  technicianCountEn?: string;
  technicianTeam?: string;
  technicianTeamEn?: string;
  hours?: string;
  hoursEn?: string;
  overnight?: string;
  overnightEn?: string;
  paymentMethods?: string;
  bestFor?: string;
  bestForEn?: string;
  processSteps?: { title: string; titleEn: string; desc: string; descEn: string }[];
  // Detail page sections
  serviceContent?: string;
  serviceContentEn?: string;
  recommendReasons?: string[];
  recommendReasonsEn?: string[];
  noticeItems?: string[];
  noticeItemsEn?: string[];
  conclusion?: string;
  conclusionEn?: string;
}

export interface Article {
  slug: string;
  title: string;
  titleEn: string;
  excerpt: string;
  excerptEn: string;
  content: string;
  contentEn: string;
  type: 'ranking' | 'guide';
  updatedAt: string;
}

export const venues: Venue[] = [

  {
    slug: 'shangpin-spa',
    name: '尚品',
    nameEn: 'Shangpin International Spa',
    tagline: '日式泡泡浴招牌・全日买一送一',
    taglineEn: 'Best value duo packages, constantly improving',
    tag: 'value',
    categories: ['高性价', '阵容', '泡泡浴'],
    aliases: '尚品水疗、尚品国际、澳门尚品',
    technicianCount: '90+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 凌晨3:00后免费独立睡房',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '性价比之王／日式泡泡浴体验',
    processSteps: [
      { title: '抵达葡京人酒店', titleEn: '', desc: '尚品国际水疗位于路氹葡京人酒店内，从机场或新区饭店过来几乎不必拉车。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '明亮整洁的沐浴泡浴区，环境高档华丽。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '免费餐饮供应，主打高端选择。', descEn: '' },
      { title: '经理推荐选技师', titleEn: '', desc: '告知经理你的喜好与预算，技师逐一面对面见面——私密、安静、不喧闹。', descEn: '' },
      { title: '招牌日式泡泡浴', titleEn: '', desc: '全澳少数专注做日式泡泡浴（ソープランド）的场馆，体验独特。', descEn: '' },
      { title: '独立睡房过夜', titleEn: '', desc: '凌晨3:00后免费独立休息房，独享私人空间安睡到天光。', descEn: '' },
    ],
    price: 1480,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.3,
    image: '/venues/shangpin.jpg',
    features: ['日式泡泡浴', '双人方案', '性价比'],
    featuresEn: ['Duo package', 'Special bath experience', 'Value'],
    highlights: [
      { icon: 'heart-handshake', title: '双人方案', titleEn: 'Duo Package', desc: '门槛友善、价格带更容易入手', descEn: 'Accessible pricing for duo experiences' },
      { icon: 'bath', title: '特色泡澡', titleEn: 'Special Bath', desc: '小房间+气垫床，有辨识度', descEn: 'Compact room with air mattress, unique experience' },
    ],
    reviewSections: [
      { title: '近期表现', titleEn: 'Recent Performance', content: '尚品近期人员配置肉眼可见地变多，现场大概能看到约20-30位在场。双人方案走的是门槛更友善、价格带更容易入手的路线，是这几个月进步幅度最大的店之一。', contentEn: 'Shangpin has visibly increased staff recently, with about 20-30 visible on-site. Their duo packages are priced accessibly, making it one of the most improved venues in recent months.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1480, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '双人方案', nameEn: 'Duo Package', price: 2280, desc: '双人体验，性价比突出', descEn: 'Duo experience, excellent value' },
    ],
    pros: ['双人方案性价比高', '近期人员数量回升', '特色泡澡有辨识度'],
    prosEn: ['Great value duo packages', 'Staff numbers recovering', 'Unique bath experience'],
    cons: ['泡澡房间偏小', '平均颜值变化不大'],
    consEn: ['Bath rooms are compact', 'Average aesthetics unchanged'],
    suitableFor: '追求双人方案性价比、想试特色泡澡的客人',
    suitableForEn: 'Those seeking value duo packages and special bath experiences',
    ranking: 1,
    longDescription: '尚品国际水疗位于路氹葡京人酒店内，是 2025 年最新登场的高端桑拿会所，以「精品化、高质感、私密体验」为核心。场馆规模适中，但欧式现代风格装潢、光线柔和，每个包厢配备独立休息区或浴池，私密度高。招牌是日式泡泡浴——目前全澳专注做这个项目的场馆不多，搭配「全日买一送一」促销，性价比极为突出。90+ 多国籍技师，不走大型走秀，而是由经理根据你的喜好与预算逐一安排见面——私密、安静、不喧闹。尚品是少数提供「凌晨 3:00 后免费独立睡房」的场馆之一，预约即送，等于玩到深夜也有独立空间睡到天光，省下一晚住宿。特别适合入住葡京人、偏好日式体验、预算中端又不爱热闹的旅客。',
    longDescriptionEn: 'Shangpin International Spa sits inside Grand Lisboa Palace in Taipa — practically no travel needed from the airport or new district hotels. Hardware is brand-new with European modern styling. The standout is "mid-range price, top-tier experience": all-day buy-one-get-one plus signature Japanese bubble bath — rare in Macau. Over 90 technicians from 8 nationalities offer wide selection. Even better, Shangpin is one of the few venues offering free private sleeping rooms after 3 AM with booking — saving you a night\'s hotel stay.',
    serviceContent: '尚品国际水疗位于路氹葡京人酒店内，以欧式现代风格装潢，空间宽敞、光线柔和，每个包厢配备独立休息区或浴池，私密度高。技师团队以中、越混合为主，整体风格偏向「气质型／名媛风」。招牌是日式泡泡浴——目前全澳专注做这个项目的场馆不多，搭配「全日买一送一」促销，性价比极为突出。不走大型走秀，而是由经理根据你的喜好与预算逐一安排见面——私密、安静、不喧闹。少数提供「凌晨 3:00 后免费独立睡房」的场馆之一，预约即送。',
    recommendReasons: ["日式泡泡浴是全澳少见的专项体验，辨识度高","全日买一送一，性价比在同等场馆中突出","凌晨 3:00 后免费独立睡房，省下一晚住宿","私密安静的选秀方式，不喧闹不拥挤","位于葡京人酒店内，路氹动线方便"],
    noticeItems: ["技师数量不及壹号、豪门等大场，某些时间段选择可能有限","泡澡房间偏小，与大场的豪华套房有差距","建议提前预约确认当日技师上班情况与泡泡浴房是否可安排"],
    conclusion: '尚品国际水疗是 2025 年值得开启的新选择——日式泡泡浴有辨识度，买一送一性价比突出，独立睡房免费送更是加分项。如果你偏好私密安静、预算中端又不爱热闹，尚品非常适合。',
    coverBadge: '性价比之王',
    coverBadgeEn: 'Best Value',
    coverImage: '/venues/covers/shang-pin-spa.webp',
    gallery: [
      '/venues/shangpin/01.webp',
      '/venues/shangpin/02.webp',
      '/venues/shangpin/03.webp',
      '/venues/shangpin/04.webp',
      '/venues/shangpin/05.webp',
      '/venues/shangpin/06.webp',
      '/venues/shangpin/07.webp',
      '/venues/shangpin/08.webp',
      '/venues/shangpin/09.webp',
      '/venues/shangpin/10.webp',
      '/venues/shangpin/11.webp',
      '/venues/shangpin/12.webp',
    ],
    galleryCaptions: [
      '尚品国际水疗的湿区设有大型按摩泡池，木质地板与柔和灯光营造放松氛围。',
      '尚品国际水疗的躺椅休息走道，以蓝光灯墙与成排电动躺椅营造沉静的休憩氛围。',
      '尚品国际水疗的休息房以镜面墙饰搭配舒适床位，提供私密的歇息环境。',
      '尚品国际水疗的私人房走廊以深蓝与大理石铺陈，尽显现代欧式格调。',
      '尚品国际水疗设有成排电动躺椅休息区，蓝光氛围让人安心放松。',
      '尚品国际水疗的躺椅休息大厅宽敞舒适，搭配大型萤幕供宾客观影歇息。',
      '尚品国际水疗的星空主题睡房，木纹墙面点缀点点繁星与粉紫霓虹灯带，私密又浪漫。',
      '尚品国际水疗的贵宾休息厅以深蓝沙发与大理石地坪呈现低调奢华。',
      '尚品国际水疗的表演大厅灯光绚烂，紫色舞台灯架打造热闹娱乐氛围。',
      '尚品国际水疗的娱乐厅以粉红灯光与价目萤幕点亮红毯舞台。',
      '尚品国际水疗的大堂以紫光阶梯与圆形镜饰，迎接宾客入场。',
      '尚品国际水疗的接待柜台以岩石墙面衬托发光金字招牌，气派十足。',
    ],
  },

  {
    slug: 'manhao-spa',
    name: '曼濠',
    nameEn: 'Man Hao Spa',
    tagline: '氹仔新区，最大选秀舞台',
    taglineEn: 'Taipa new area, largest selection stage',
    tag: 'new',
    ranking: 2,
    categories: ['新场','阵容'],
    aliases: '曼濠桑拿、曼豪桑拿、漫濠水疗、澳门曼濠水疗',
    technicianCount: '多国籍技师团队',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '14:00 – 04:00',
    overnight: '不可过夜 — 过渡期暂不提供过夜，即将恢复24小时',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '最大走秀舞台／氹仔奢华首选',
    processSteps: [
      { title: '抵达君怡酒店', titleEn: '', desc: '曼濠水疗位于氹仔君怡酒店——距离路氹城仅5分钟车程。大堂以云石背景上的金色皇冠MH标志迎宾；前台登记后，由礼宾接待领取手牌。', descEn: '' },
      { title: '奢华更衣室', titleEn: '', desc: '卡拉拉云石主墙面、金色搭扣订制木柜、软垫长椅，所有硬件贯彻皇者奢华格调。', descEn: '' },
      { title: '沐浴与湿区', titleEn: '', desc: '深色马赛克瓷砖与绿纹云石搭配，配备多个冲凉位置及独立泡池，空间宽敞。', descEn: '' },
      { title: '用餐厅', titleEn: '', desc: '云石桌面用餐厅享用免费餐饮——静雅的酒店级座椅配私人酒吧氛围。', descEn: '' },
      { title: '全澳最大走秀大厅', titleEn: '', desc: '多层玻璃栏杆走秀大厅配深蓝霓虹灯光，全澳最大规模的走秀体验，挑选技师成为主场体验。', descEn: '' },
      { title: '整合式套房与招牌水床', titleEn: '', desc: '奢华睡房配置结合招牌红色水床及戏剧性聚光灯效果，睡房与水床设于同一私密房间。', descEn: '' },
      { title: '60分钟服务', titleEn: '', desc: '国际技师团队涵盖亚洲及欧洲多国背景，按摩风格相应配对。灯光、音响、浴缸均可在房内操控。', descEn: '' },
      { title: '休息区', titleEn: '', desc: '专属星空休息区——光线柔和、配备奢华躺椅。现为过渡期营业时段，24小时及过夜服务即将恢复。', descEn: '' },
    ],
    price: 1580,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.2,
    image: '/venues/manhao.jpg',
    features: ['大舞台', '五星房间', '新区'],
    featuresEn: ['Large stage', 'Five-star rooms', 'New district'],
    highlights: [
      { icon: 'theater', title: '最大舞台', titleEn: 'Largest Stage', desc: '拥有全澳最大的选秀舞台，场面壮观', descEn: 'The largest selection stage in Macau, spectacular' },
      { icon: 'bed-double', title: '五星房间', titleEn: 'Five-Star Rooms', desc: '五星级酒店客房般的房间体验', descEn: 'Five-star hotel room-like experience' },
    ],
    reviewSections: [
      { title: '新区新体验', titleEn: 'New District Experience', content: '曼濠是氹仔新区的最新桑拿房，拥有全澳最大的选秀舞台，场面壮观。提供五星级酒店客房般的房间，提升整体体验。', contentEn: 'Man Hao is the newest sauna in Taipa\'s new district, featuring the largest selection stage in Macau. Five-star hotel room-like accommodations enhance the overall experience.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1580, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '五星体验', nameEn: 'Five-Star Experience', price: 2580, desc: '五星级房间+完整体验', descEn: 'Five-star room + full experience' },
    ],
    pros: ['最大选秀舞台', '五星级房间体验', '新区新设施'],
    prosEn: ['Largest selection stage', 'Five-star room experience', 'New district facilities'],
    cons: ['氹仔位置稍远', '新店口碑待积累'],
    consEn: ['Taipa location slightly remote', 'New venue reputation still building'],
    suitableFor: '追求大场面选秀、五星房间体验的客人',
    suitableForEn: 'Those seeking grand selection stages and five-star rooms',
    coverBadge: '最新 & 最大舞台',
    coverBadgeEn: 'Newest & Largest Stage',
    coverImage: '/venues/covers/manhao-spa.webp',
    longDescription: '曼濠水疗不是普通新场，而是氹仔君怡酒店的「场景型新场」——金色皇冠 MH 标志映于云石墙面，金色搭扣订制木柜、云石餐厅大堂与壁画回廊一脉相承，整体格调靠近精品酒店多于传统桑拿。招牌是全澳最大规模的走秀接待大厅——多层玻璃栏杆走道配深蓝霓虹灯光，把挑选技师化为主场体验而非例行步骤，建议 19:00 后抵场感受完整走秀氛围。红色水床是曼濠最有记忆点的房型符号——整合式套房将睡房与水床设于同一私密空间，单束戏剧性聚光灯下尽显格调。由涵盖亚洲与欧洲八国背景的国际技师团队度身提供舒缓按摩。免费餐饮区采用云石桌面与酒店级座椅，不是普通桑拿食堂。设有星空休息区可过夜，目前为过渡期营业时段，24 小时及过夜服务即将恢复。加收一成服务费。',
    longDescriptionEn: 'Manhao Spa is not an ordinary new venue — it\'s a "scene-driven" new establishment at Taipa\'s Grand Inn Hotel. Golden crown MH logo on marble walls, gold-buckle custom cabinetry, marble dining hall and mural corridors all echo a boutique hotel more than a traditional sauna. The signature: Macau\'s largest selection hall with multi-level glass railings and deep blue neon, turning technician selection into a main-stage experience — best after 19:00. The red water bed is Manhao\'s most memorable room symbol: integrated bedroom + water bed suites with dramatic spotlighting. International technician team spans 8 Asian and European backgrounds. Complimentary dining area features marble tabletops and hotel-grade seating. Stargazer rest area available; currently in transitional hours with 24-hour operation and overnight service resuming soon. 10% service charge.',
    serviceContent: '曼濠水疗位于氹仔君怡酒店，是 2026 年新开业的「场景型高端场」。金色皇冠 MH 标志映于云石墙面，大堂走精品酒店式会所路线。最大辨识度是大型走秀接待大厅——多层玻璃栏杆走道搭配深蓝霓虹灯光，把选秀做成视觉感极强的主场体验。招牌红色水床是曼濠最有记忆点的房型符号，客房采用「睡房结合水床」整合式套房设计，配有舞台感灯光。用餐区采用云石桌面与酒店级座椅，氛围接近精品酒店。另设星空休息区，可作过夜留宿安排。',
    recommendReasons: ["2026 年 5 月全新开业，装修设备全新，话题度高","大型走秀接待大厅辨识度极强，选秀体验是核心卖点","红色水床整合式套房，有明确视觉符号，差异化明显","位于氹仔君怡酒店，住氹仔或路氹动线方便","云石桌面用餐区与星空休息区，整体体验完整"],
    noticeItems: ["新场稳定度仍需观察，完整公开价目资讯不多","水床与套房安排需提前确认，热门时段可能需要排队","技师时段为 17:00–06:00，太早到场可能状态不完整","另收 10% 服务费"],
    conclusion: '曼濠水疗不是便宜场，而是氹仔新派高端桑拿里主打走秀大厅、红色水床和皇者气派的一间新场。想稳看壹号，想质感看帝湖，想效率看豪门，想场景感——就看曼濠。',
    gallery: [
      '/venues/manhao/01.webp',
      '/venues/manhao/02.webp',
      '/venues/manhao/03.webp',
      '/venues/manhao/04.webp',
      '/venues/manhao/05.webp',
      '/venues/manhao/06.webp',
      '/venues/manhao/07.webp',
      '/venues/manhao/08.webp',
      '/venues/manhao/09.webp',
      '/venues/manhao/10.webp',
      '/venues/manhao/11.webp',
      '/venues/manhao/12.webp',
    ],
    galleryCaptions: [
      '曼濠水疗的整合式睡房，黑金主调搭配云石墙与金色圆镜尽显皇者气派。',
      '曼濠水疗著名的蓝光选秀大厅，挑高楼层与玻璃栏杆是全澳门桑拿瞩目焦点。',
      '曼濠水疗招牌的红色水床套房，深色云石墙与斜射光束营造私密氛围。',
      '曼濠水疗的整合式睡房，淡雅山水壁画配金线天花，舒适大床旁设按摩椅。',
      '曼濠水疗通往套房的走廊，柔光照映满墙树影壁画，地毯沉稳雅致。',
      '曼濠水疗的星空顶休息厅，蓝纹云石墙搭配舒适躺椅，适合静心放松。',
      '曼濠水疗的餐饮区，云石餐桌与金色屏风搭配长型吧台，雅致而舒适。',
      '曼濠水疗大堂的金色皇冠MH标志，镶于卡拉拉云石墙上尽显尊贵。',
      '曼濠水疗的更衣室，两侧木质置物柜环绕云石端墙，中央软垫长凳宽敞舒适。',
      '曼濠水疗的沐浴区，按摩浴池与蒸气房环绕云石墙，水疗设施一应俱全。',
      '曼濠水疗的蒸气淋浴间，深色马赛克墙搭配躺台与木桶，沐浴体验讲究。',
      '曼濠水疗的云石淋浴隔间，灰调云石墙配金色花洒，洁净而具质感。',
    ],
  },

  {
    slug: 'jiuhao-spa',
    name: '玖号',
    nameEn: 'Jiu Hao Spa',
    tagline: '最新开业，日韩资源丰富',
    taglineEn: 'Newly opened, rich Japanese & Korean lineup',
    tag: 'new',
    categories: ['新场','阵容'],
    aliases: '玖号水疗、玖号桑拿、澳门玖号',
    technicianCount: '80+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 免费休息区',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '2026最新开幕／日韩阵容强',
    processSteps: [
      { title: '抵达御龙酒店', titleEn: '', desc: '玖号水疗于2026年4月揭幕，位于市中心御龙酒店，交通极为便利。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '簇新硬件，现代奢华风格更衣区及沐浴湿区。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '主打高端选择的免费餐饮，全程供应。', descEn: '' },
      { title: '主舞台走秀', titleEn: '', desc: '娱乐大厅以招牌主舞台为核心，专业灯光配LED荧幕，技师走秀呈现全澳最具现代感的视觉效果。', descEn: '' },
      { title: '情境主题房', titleEn: '', desc: '多款情境主题房，各有专属色调——红色、粉紫、蓝紫，星空天花沉浸体验。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '作为全澳最新场馆，环境安静不拥挤，休息区舒适过夜。', descEn: '' },
    ],
    price: 1380,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.1,
    image: '/venues/jiuhao.jpg',
    features: ['日韩路线', '新开业', '道具丰富'],
    featuresEn: ['Japanese & Korean lineup', 'Newly opened', 'Rich props'],
    highlights: [
      { icon: 'sparkles', title: '最新开业', titleEn: 'Newly Opened', desc: '澳门最新开业的桑拿房', descEn: 'The newest sauna venue in Macau' },
      { icon: 'flag', title: '日韩丰富', titleEn: 'JP & KR Rich', desc: '日本韩国资源丰富，也是最便宜的日韩桑拿房', descEn: 'Rich Japanese and Korean lineup, most affordable JP/KR venue' },
    ],
    reviewSections: [
      { title: '新店印象', titleEn: 'New Venue Impression', content: '玖号是澳门最新开业的桑拿房，主打日本韩国资源丰富，也是澳门最便宜的日韩桑拿房。道具丰富，是新店的一大亮点。', contentEn: 'Jiu Hao is the newest sauna in Macau, featuring a rich Japanese and Korean lineup at the most affordable pricing. Rich props are a highlight of this new venue.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1380, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '日韩套餐', nameEn: 'JP/KR Package', price: 1880, desc: '日韩路线体验', descEn: 'Japanese & Korean lineup experience' },
    ],
    pros: ['最新开业设施新', '日韩资源丰富', '价格便宜'],
    prosEn: ['Newly opened with new facilities', 'Rich Japanese & Korean lineup', 'Affordable pricing'],
    cons: ['新店稳定性待观察', '整体经验数据少'],
    consEn: ['Stability yet to be observed', 'Limited experience data'],
    suitableFor: '想体验新店、偏好日韩路线的客人',
    suitableForEn: 'Those who want to try new venues and prefer JP/KR lineup',
    coverBadge: '最新 & 最热门',
    coverBadgeEn: 'Newest & Hottest',
    coverImage: '/venues/covers/number-nine-sauna.webp',
    longDescription: '玖号水疗 2026 年 4 月全新开业，落脚澳门半岛市中心御龙酒店，是新一波顶级场馆的代表。场内以金色与大理石铺陈的现代奢华风格，娱乐大厅架起剧场级舞台与 LED 主屏，专业灯光配荧幕，把技师接待做成沉浸式视觉秀——走秀环节呈现全澳最具现代感的视觉效果。八国约 80+ 技师中日韩阵容尤其抢眼，在强劲的日韩技师中挑一位合眼缘的，享受招牌日式与韩式按摩手法。多款情境主题房各有专属色调——红色、粉紫、蓝紫——星空天花将你带入沉浸而静谧的放松。作为全澳最新场馆，环境安静不拥挤，现正推出开业优惠，双人服务更可享买一送一。24 小时营业、可过夜。',
    longDescriptionEn: 'Opened April 2026, the earliest of the year\'s three major new venues, with perfect reviews. Located in downtown Macau Peninsula. The venue takes a contemporary luxury approach, with a theater-grade stage and LED main screen in the entertainment hall, turning technician introductions into an immersive visual show. Among 80+ technicians from 8 countries, the Japanese and Korean lineup is especially notable. 24-hour operation with overnight stays, public pricing from MOP 2,299 to 6,999.',
    serviceContent: '玖号水疗 2026 年 4 月全新开业，落脚澳门半岛市中心御龙酒店。场内以金色与大理石元素作为主视觉，大堂与走廊空间宽敞，整体观感偏华丽明亮。主沐浴区配备大型按摩浴缸与较新式桑拿设施，灯光偏柔和放松。共享休息区配置躺椅与休憩空间，餐饮区提供多样化选择。特色是「舞台选秀，灯光全面，更能看清楚技师全身上下」，日韩资源丰富，主打澳门最便宜的日韩体验。',
    recommendReasons: ["2026 年 4 月全新开业，装修设备全新，奢华感强","舞台选秀灯光充足，挑选更直观准确","日韩技师资源丰富，价格是全澳最便宜的日韩之一","位于市中心御龙酒店，交通便利","综合型娱乐水疗空间，不只是桑拿，更适合社交与放松"],
    noticeItems: ["新场开业不久，技师数量与稳定度仍需观察","另收 10% 服务费","建议提前预约确认当日技师上班情况"],
    conclusion: '玖号水疗是 2026 年新派水疗会所的代表，把澳门传统桑拿的流程感和现代高级水疗空间的舒适度结合在一起。如果你重视环境够新、装修够体面、日韩资源丰富，玖号值得列入名单。',
    ranking: 3,
    gallery: [
      '/venues/jiuhao/01.webp',
      '/venues/jiuhao/02.webp',
      '/venues/jiuhao/03.webp',
      '/venues/jiuhao/04.webp',
      '/venues/jiuhao/05.webp',
      '/venues/jiuhao/06.webp',
      '/venues/jiuhao/07.webp',
      '/venues/jiuhao/08.webp',
      '/venues/jiuhao/09.webp',
      '/venues/jiuhao/10.webp',
      '/venues/jiuhao/11.webp',
      '/venues/jiuhao/12.webp',
    ],
    galleryCaptions: [
      '玖号水疗的红色情境主题房，巨型圆床搭配环形灯光，氛围奢华抢眼。',
      '玖号水疗的剧场级选秀舞台，霓虹灯光与巨型LED星形屏炫目登场。',
      '玖号水疗的紫色极光主题房，星河投影铺满天花，氛围梦幻放松。',
      '玖号水疗的粉红星空主题房，LED光带与满天星投影营造迷醉氛围。',
      '玖号水疗的水床套房，蓝纹大理石墙面配独立花洒，私密又贴心。',
      '玖号水疗的休息大厅，成排电动躺椅与蓝色地画，候钟放松首选。',
      '玖号水疗的按摩躺椅休憩室，柔和灯光与地毯花纹尽显五星质感。',
      '玖号水疗的用餐区，大理石长桌配格栅屏风，环境宽敞明亮。',
      '玖号水疗的更衣室，木纹置物柜透出蓝光，搭配软凳整洁大气。',
      '玖号水疗的高级更衣区，毛巾与沐浴备品陈列整齐，吊灯气派十足。',
      '玖号水疗的淋浴梳洗区，绿色马赛克墙配圆镜与独立洗手台，干净清爽。',
      '玖号水疗进驻御龙酒店，紫金色大楼外观醒目，交通便利易寻。',
    ],
  },

  {
    slug: 'juheng-sauna',
    name: '巨亨',
    nameEn: 'Ju Heng Sauna',
    tagline: '奢华大理石，情趣制服丰富',
    taglineEn: 'Luxury marble, rich costume selection',
    tag: 'premium',
    categories: ['新场', '阵容'],
    aliases: '巨亨桑拿、巨亨水疗、澳门巨亨',
    technicianCount: '多国籍技师团队',
    technicianTeam: '台、日、韩、越、泰、中、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 付费独立休息房',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '2026最新奢华／3.2亿巨作',
    processSteps: [
      { title: '抵达澳门半岛场馆', titleEn: '', desc: '巨亨桑拿于2026年5月15日揭幕，斥资港币8,000万打造，位于澳门半岛。', descEn: '' },
      { title: '管家式接待', titleEn: '', desc: '从大堂气味、灯光色温到走道尺度都更靠近五星酒店而非传统桑拿，管家全程打点。', descEn: '' },
      { title: '大理石浴池', titleEn: '', desc: '沉入温热的大理石浴池，在酒店级主题套房里安顿下来，一切交给专属管家打理。', descEn: '' },
      { title: '挑选技师', titleEn: '', desc: '台湾网红与日本明星级技师领衔的多国籍团队，从台式、日式按摩到招牌水床特色房型。', descEn: '' },
      { title: '酒店级主题套房', titleEn: '', desc: '酒店级主题套房、整片大理石浴池，静雅私密的氛围是这个价位带最稀缺的元素。', descEn: '' },
      { title: '独立休息房过夜', titleEn: '', desc: '付费独立过夜房，格调用餐厅，开业期两位技师同行买一送一优惠。', descEn: '' },
    ],
    price: 1680,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 4.0,
    image: '/venues/juheng.jpg',
    features: ['大理石装修', '情趣制服', '过夜区'],
    featuresEn: ['Marble interior', 'Costume selection', 'Overnight area'],
    highlights: [
      { icon: 'castle', title: '大理石装修', titleEn: 'Marble Interior', desc: '奢华大理石装修风格，质感出众', descEn: 'Luxury marble interior, outstanding texture' },
      { icon: 'shirt', title: '情趣制服', titleEn: 'Costume Selection', desc: '提供情趣制服任客挑选，可提前说明要求', descEn: 'Costume selection available, custom requests accepted' },
    ],
    reviewSections: [
      { title: '奢华体验', titleEn: 'Luxury Experience', content: '巨亨以奢华大理石装修风格著称，质感出众。提供情趣制服任客挑选，客人也可提前说明要求提前购置。另有独立过夜区域，让您舒适过夜。', contentEn: 'Ju Heng is known for its luxury marble interior with outstanding texture. Costume selection is available with custom request options. Separate overnight area ensures comfortable rest.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1680, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '制服套餐', nameEn: 'Costume Package', price: 2180, desc: '含制服体验', descEn: 'Includes costume experience' },
    ],
    pros: ['大理石装修质感好', '情趣制服选择多', '可独立过夜'],
    prosEn: ['Quality marble interior', 'Rich costume selection', 'Independent overnight area'],
    cons: ['人员数量一般', '位置偏僻'],
    consEn: ['Average staff numbers', 'Remote location'],
    suitableFor: '追求装修质感、制服体验、需要过夜的客人',
    suitableForEn: 'Those who value interior quality, costume experiences, and overnight stays',
    coverBadge: '最新 & 尊贵',
    coverBadgeEn: 'Newest & Most Prestigious',
    coverImage: '/venues/covers/empire-sauna.webp',
    longDescription: '巨亨桑拿是 2026 年 5 月最新开业的奢华场馆，传闻装修花了 8000 万港币——一踏进门，城市喧嚣便瞬间远去。沉入温热的大理石浴池，在酒店级主题套房里安顿下来，一切交给专属管家打理，你只需尽情放空。走秀大厅与壹号、曼濠同属「大场面派」，多国籍技师阵容中台湾网红与日本明星级技师领衔，挑一位合眼缘的，再选一种顺心情的手法：台式、日式、韩式、欧式按摩，到招牌水床任你享受。价格分层较多，从热带雨林 MOP 3,999 到宝岛首席 MOP 9,988 不等，另有双人价与买一送一活动。主题房装修比一般桑拿精致许多，餐饮品质不俗，免费供应。加收一成服务费。24 小时营业、可过夜，独立休息房睡得安稳。',
    longDescriptionEn: 'Unveiled May 15, Ju Heng Sauna is an HKD 80 million luxury creation. Everything feels closer to a five-star hotel than a traditional sauna — from lobby scent to hallway scale. Hotel-grade themed suites, full marble bath pools, and butler-style reception. The lineup features internet-famous and star-level technicians from Taiwan, Japan, Korea, and Europe. Pricing is layered: from Tropical Rain Forest at MOP 3,999 to Island Chief at MOP 9,988, with duo pricing and buy-one-get-one offers. Signature water bed rooms. Themed rooms are notably more refined than typical saunas. Complimentary dining. 10% service charge. 24-hour operation with independent overnight rooms.',
    serviceContent: '巨亨桑拿是 2026 年 5 月最新开业的奢华场馆，传闻装修花了 8000 万港币——大理石浴池、酒店级主题套房、水床房、用餐休息区一应俱全，走高端奢华路线。价格分层多，从热带雨林 3,999 到宝岛首席 9,988，涵盖台式、欧式、日式、韩式等分类。特色是水床房和买一送一活动——不同项目的买一送一价格不同，需提前确认规则。另有双人价和加时价选项，适合多人同行或想延长体验的客人。',
    recommendReasons: ["2026 年 5 月最新开业，装修全新，大理石高端奢华路线","水床房是核心卖点，整合式套房设计有记忆点","买一送一活动和双人价，适合两人同行","位于澳门半岛市中心，交通便利","可过夜休息，用餐区设备完善"],
    noticeItems: ["另收 10% 服务费，预算需多抓一成","买一送一规则因项目而异，需提前确认是否限时段、是否同项目","水床房热门时段可能需提前预约安排","新场仍属试运营期，建议提前确认当日状态再决定前往"],
    conclusion: '巨亨桑拿是一间更适合「提前规划」的新派高端场。核心不是低价，而是高端新场环境、大理石浴池、水床房与买一送一玩法。预约问清楚，体验会顺很多；临场才问，最容易花冤枉钱。',
    ranking: 4,
    gallery: [
      '/venues/juheng/01.webp',
      '/venues/juheng/02.webp',
      '/venues/juheng/03.webp',
      '/venues/juheng/04.webp',
      '/venues/juheng/05.webp',
      '/venues/juheng/06.webp',
      '/venues/juheng/07.webp',
      '/venues/juheng/08.webp',
      '/venues/juheng/09.webp',
      '/venues/juheng/10.webp',
      '/venues/juheng/11.webp',
      '/venues/juheng/12.webp',
    ],
    galleryCaptions: [
      '巨亨桑拿白云石主题套房——独立按摩床搭配暖金壁灯与云石浴墙，澳门半岛五星级水疗的招牌房型。',
      '巨亨桑拿双圆形云石浴池，木格栅天花搭配绿意造景，是入场泡浴热身的招牌水区。',
      '巨亨桑拿海洋LED水床套房，蓝海光幕墙衬托落地镜面按摩区，招牌水床特色房型。',
      '巨亨桑拿金光天花云石套房，六角地砖与独立按摩床交织出私密尊贵感。',
      '巨亨桑拿棕云石私人冲凉房，黑金雨淋花洒配木纹饰墙，服务前后从容梳洗。',
      '巨亨桑拿森林光幕主题睡房，蕨叶壁画与柔光间照，适合过夜留宿到隔天再飞回台湾。',
      '巨亨桑拿休息躺椅区，自然光幕墙搭配水晶吊灯，候场与服务后放松的首选空间。',
      '巨亨桑拿咖啡休憩区，云石圆桌上的手冲咖啡与整排躺椅，安静歇脚的角落。',
      '巨亨桑拿蓝光餐饮大厅，云石餐桌与挑高镜面天花，免费餐饮全程供应。',
      '巨亨桑拿挑高中庭餐厅，蓝色光幕与水晶吊灯交织出酒店级用餐空间。',
      '巨亨桑拿云石大堂与迎宾楼梯，绿植造景衬托现代禅意的入场动线。',
      '巨亨桑拿艺术相框墙休息厅，云石楼梯与订制沙发营造的格调候场空间。',
    ],
  },

  {
    slug: 'supreme-sauna',
    name: '极品',
    nameEn: 'Supreme Sauna',
    tagline: '24小时营业，AV主题房沉浸体验',
    taglineEn: '24hr open, Macau boutique sauna',
    tag: 'value',
    categories: ['高性价'],
    aliases: '极品桑拿、澳门极品',
    technicianCount: '40+ 位技师',
    technicianTeam: '中、越、泰、日、韩、俄',
    hours: '24小时',
    overnight: '可过夜 — 免费休息区',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '24小时营业／主题情境房／精品级技师',
    processSteps: [
      { title: '抵达英皇娱乐酒店', titleEn: '', desc: '极品桑拿位于澳门半岛英皇娱乐酒店本馆，交通便利。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '整洁的更衣区及沐浴空间，环境紧凑精致。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '免费餐饮24小时供应，随时补充体力。', descEn: '' },
      { title: '经理面选技师', titleEn: '', desc: '约40位技师走「少而精」路线，由经理逐位面对面介绍，外型与服务都经过筛选。', descEn: '' },
      { title: 'AV主题情境房', titleEn: '', desc: 'DJ室、SM室、办公室、卡拉OK、医院情境房，可指定技师穿着各种服装，自订互动内容，主题房加收MOP 400。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '24小时可过夜休息区，氛围安静不拥挤。', descEn: '' },
    ],
    price: 1280,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 3.9,
    image: '/venues/supreme.jpg',
    features: ['24小时营业', 'AV主题房'],
    featuresEn: ['24hr Open', 'AV Theme Rooms'],
    highlights: [
      { icon: 'clover', title: '小而稳', titleEn: 'Small & Steady', desc: '适合临时想去、不追求量级的人', descEn: 'For spontaneous visits, not about quantity' },
      { icon: 'globe', title: '欧美亮点', titleEn: 'Western Highlights', desc: '偶有出彩的欧美路线', descEn: 'Occasional standout Western lineup' },
    ],
    reviewSections: [
      { title: '整体印象', titleEn: 'Overall Impression', content: '极品不算走量大、选择超多的场子，而比较像是小而稳、看当天运气的类型。师傅工颜值还不错，技师整体比较一般。偶有出彩的欧美路线，但非常吃当天排班。', contentEn: 'Supreme is not about volume or vast selection — it is small, steady, and luck-dependent. Master craftsmen have decent aesthetics, while technicians are average. Occasional standout Western lineup, but very schedule-dependent.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1280, desc: '单人基础服务', descEn: 'Standard single service' },
    ],
    pros: ['冷门备选不拥挤', '偶有欧美路线惊喜', '师傅工颜值不错'],
    prosEn: ['Uncrowded alternative', 'Occasional Western lineup surprise', 'Decent master craftsman aesthetics'],
    cons: ['人员数量偏少', '无明显特色玩法', '整体普通看缘分'],
    consEn: ['Limited staff numbers', 'No distinctive features', 'Average overall, luck-dependent'],
    suitableFor: '想补一间冷门备选、不在乎量级的客人',
    suitableForEn: 'Those wanting an uncrowded backup option',
    coverBadge: '24小时',
    coverBadgeEn: '24 Hours',
    coverImage: '/venues/covers/the-excellent-sauna.webp',
    longDescription: '极品桑拿自 2017 年在英皇娱乐酒店开幕后，一直以「高品质＋创新主题房」著称，是澳门性价比最高、体验感最好的精品级桑拿之一。最大亮点是全新打造的 AV 主题房——DJ 室、SM 室、办公室、卡拉 OK、医院情境房，房型不多但每间都极具沉浸感，是喜欢角色扮演玩家的必访之地。可指定技师穿着各种服装、自订游戏方式与互动内容，主题房加收 400 澳门元。极品最独特之处是 24 小时营业且全天候有技师在班——澳门大多数桑拿要下午三点后才陆续有人上班，唯有极品随时进场都能匹配到技师，对白天来澳门的商务客或行程紧凑的旅客而言不可替代。技师 40+ 涵盖八国，走「少而精」路线，颜值、身材与互动能力都属澳门较高水准。环境不拥挤不混乱，氛围佳，是靠品质取胜而非人海战术的会所。',
    longDescriptionEn: 'The biggest advantage is "24-hour operation" — located in the Emperor Entertainment Hotel on Macau Peninsula, whether you arrive on a red-eye flight at midnight or have free time during the day, you can walk in anytime. The hardware highlight is brand-new themed scenario rooms: DJ studio, office, cinema, hospital and more. 40+ technicians from 8 countries, introduced one by one via face-to-face selection by the manager. Free dining available 24 hours, overnight stays welcome.',
    serviceContent: '极品桑拿自 2017 年在英皇娱乐酒店开幕后，一直以「高品质＋创新主题房」著称，是澳门性价比最高、体验感最好的精品级桑拿之一。最大亮点是全新打造的 AV 主题房——DJ 室、SM 室、办公室场景、卡拉 OK 室、医院情境房，房型不多但每一间都极具沉浸感。同时具备水床服务＋角色扮演主题房，客人可指定技师穿着各种服装、自订游戏方式与互动内容。技师阵容包含中、越、泰、日、韩、俄，人数 40+ 左右但每位都是严格挑选的精品级别。主题房加收 400 澳门元，指定颜色丝袜另加 200。',
    recommendReasons: ["精品级技师——少而精，每位都是严选，颜值、身材与互动能力属澳门较高水准","24 小时营业——澳门唯一「随时都有技师」的场馆，白天来也能匹配到技师","主题房沉浸感强，房间质感优，玩起来爽度高","不拥挤、不混乱——客流稳定，体验舒适","无额外服务费，比许多场子更透明"],
    noticeItems: ["使用主题房需额外加收 400 澳门元，指定丝袜另加 200","技师数量只有 40+ 左右，选择面不及壹号、豪门等大场","主题种类不如东方皇堡那么多，但可玩性反而更强——更注重沉浸感"],
    conclusion: '极品最吸引人的不是规模，而是「体验感」。环境美、食物好、氛围佳、技师精挑细选，是澳门少见能做到不靠人海战术、靠品质取胜的会所。如果你重视品质、不喜欢吵杂、喜欢主题房，极品绝对是澳门最值得推荐的前 3 名。',
    ranking: 5,
    gallery: [
      '/venues/supreme/01.webp',
      '/venues/supreme/02.webp',
      '/venues/supreme/03.webp',
      '/venues/supreme/04.webp',
      '/venues/supreme/05.webp',
      '/venues/supreme/06.webp',
      '/venues/supreme/07.webp',
      '/venues/supreme/08.webp',
      '/venues/supreme/09.webp',
      '/venues/supreme/10.webp',
      '/venues/supreme/11.webp',
      '/venues/supreme/12.webp',
    ],
    galleryCaptions: [
      '极品桑拿招牌救护车主题房，红砖情境搭配按摩水床超吸睛。',
      '极品桑拿入口大堂，「The Excellent」发光招牌与雕花木墙迎宾。',
      '极品桑拿馆内走廊，马赛克地砖与木质墙面串连各主题房。',
      '极品桑拿选秀休息区，皮革躺椅成排，旁设柜台方便登记。',
      '极品桑拿紫色VIP包厢，环形天花灯与大型皮沙发营造私密感。',
      '极品桑拿马赛克花砖私人房，配备按摩水床与独立淋浴。',
      '极品桑拿蓝光浴池水区，挑高采光搭配躺椅供泡浴放松。',
      '极品桑拿梳妆区，钻石切面金属墙与镜面灯带整理仪容。',
      '极品桑拿更衣室，整排实木置物柜与皮革长凳宽敞舒适。',
      '极品桑拿休息区，木格天花搭配躺椅与地毯供入睡小憩。',
      '极品桑拿用餐区，金纹大理石地搭配卡座供休息进餐。',
      '极品桑拿套房睡房，皮革软包床头与大理石地，适合过夜休息。',
    ],
  },

  {
    slug: 'golden-fortress-spa',
    name: '皇堡',
    nameEn: 'Orient Palace Spa',
    tagline: '澳门最强剧本杀桑拿，AV主题房角色扮演圣地',
    taglineEn: 'The atmosphere champion',
    tag: 'premium',
    categories: ['主题房', '阵容'],
    aliases: '东方皇堡、皇堡水疗、澳门皇堡',
    technicianCount: '60+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 免费躺椅休息区',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '主题房鼻祖／情境体验首选',
    processSteps: [
      { title: '抵达澳门半岛场馆', titleEn: '', desc: '东方皇堡水疗位于澳门半岛，由晋会MCLUB同一营运团队打造。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '沐浴区配备浴池、干湿蒸房，可边泡澡边观察挑选技师。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '免费餐饮全程供应，边享用边从容挑选。', descEn: '' },
      { title: '自由浏览挑选', titleEn: '', desc: '自由浏览挑选模式，没有固定介绍时间、毫无压力。', descEn: '' },
      { title: '20+主题情境房', titleEn: '', desc: '监狱审讯室、教室、医院、救护车、飞机舱、办公室、拳击场等20多款精心布置的主题房间。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '大堂躺椅过夜休息，或选择免费睡眠区。', descEn: '' },
    ],
    price: 1880,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 4.6,
    image: '/venues/huangbao/01.jpg',
    gallery: [
      '/venues/huangbao/gallery-01.webp',
      '/venues/huangbao/gallery-02.webp',
      '/venues/huangbao/gallery-03.webp',
      '/venues/huangbao/gallery-04.webp',
      '/venues/huangbao/gallery-05.webp',
      '/venues/huangbao/gallery-06.webp',
      '/venues/huangbao/gallery-07.webp',
      '/venues/huangbao/gallery-08.webp',
      '/venues/huangbao/gallery-09.webp',
    ],
    features: ['高颜值', '沉浸互动', '主题房'],
    featuresEn: ['High aesthetics', 'Immersive atmosphere', 'Themed interaction'],
    highlights: [
      { icon: 'gem', title: '气质成套', titleEn: 'Complete Aesthetics', desc: '整体呈现做得很完整，从外在到仪态', descEn: 'Complete presentation from appearance to demeanor' },
      { icon: 'heart', title: '沉浸氛围', titleEn: 'Immersive Vibe', desc: '颜值+氛围+沉浸感是核心竞争力', descEn: 'Aesthetics, atmosphere, and immersion are core strengths' },
    ],
    reviewSections: [
      { title: '气质路线', titleEn: 'Aesthetic Route', content: '皇堡让人印象深的点，不只是个别人员的外形，而是整体呈现做得很完整：从外在条件到仪态、到现场气场，普遍都能维持在高水准。', contentEn: 'What impresses about Orient Palace is not just individual appearance, but the complete presentation: from physical attributes to demeanor and on-site presence, consistently maintained at a high level.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1880, desc: '50分钟基础服务', descEn: '50-minute standard service' },
      { name: 'VIP套餐', nameEn: 'VIP Package', price: 3880, desc: '沉浸式主题体验', descEn: 'Immersive themed experience' },
    ],
    pros: ['整体气质与颜值高', '沉浸式氛围体验', '外形一致性强'],
    prosEn: ['High overall aesthetics and demeanor', 'Immersive atmosphere', 'Strong visual consistency'],
    cons: ['服务体感因人而异', '无硬体玩法噱头'],
    consEn: ['Service quality varies by pairing', 'No hardware gimmicks'],
    suitableFor: '追求颜值、气质、氛围与沉浸感的客人',
    suitableForEn: 'Those who value aesthetics, ambiance, and immersive experiences',
    ranking: 6,
    longDescription: '东方皇堡水疗是澳门最早引入 AV 情景主题房与剧本杀玩法的桑拿会所，被许多老司机公认为「澳门情境体验第一名」。场内拥有超过 20 种沉浸式主题场景——监狱、审讯室、教室、医院、救护车、飞机舱、办公室、拳击场、高尔夫球场等，每间都有完整布景、道具与服饰，踏进房间就像走进小电影片场。采用自由浏览挑选模式，没有固定走秀时间，你可以边泡澡、边看技师表演互动，从容挑选心仪技师，毫无压力。60 多位来自八个国家的技师都经过角色培训和场景训练，能快速配合剧情，互动自然投入。房间比一般桑拿大 2–3 倍，非常适合激烈互动与情境扮演。另收 15% 服务费。最适合钟情情境主题、追求新鲜刺激、想当小电影男主角的中端预算客人。',
    longDescriptionEn: 'Orient Palace Spa is the pioneer of themed scenario rooms in Macau, the first to make scene rooms a signature, and remains the go-to choice for scenario enthusiasts. Over twenty themed rooms lineup: prison, interrogation, classroom, hospital, ambulance, gym, airplane cabin, restaurant, office, golf course, boxing ring, car wash, and more — all with authentic sets, props, and costumes. Over 60 multi-national technicians (TW/JP/KR/VN/TH/RU/UA/local). 24-hour operation with overnight stays and a free sleeping area. Public room rates from MOP 2,388 to 6,498. For returning visitors wanting a different experience, this is the most direct answer.',
    serviceContent: '东方皇堡是澳门最早引入 AV 情景主题房与剧本杀玩法的桑拿会所，拥有超过 20 种沉浸式主题场景——监狱、审讯室、医院、教室、飞机舱、办公室、健身房、大巴车、拳击场等，每种剧本都有对应服装与道具，技师经过剧情桥段训练，互动自然、投入度高。属于「表演型」桑拿，女孩在入口及休息区待命，可边泡桑拿边看表演，看到喜欢的直接示意经理安排。技师来自中国、台湾、日本、韩国、越南等，外型一致性强，颜值水准稳定。',
    recommendReasons: ["澳门主题房间种类最多，超过 20 种沉浸式剧本场景，沉浸度 100%","房间比一般桑拿房大 2～3 倍，动作施展空间充足","自由设计流程，剧本想怎么玩就怎么玩，技师能完美配合甚至惊喜发挥","日韩系技师颜值高、气质好、投入剧本表演自然","另收 15% 服务费，但整体体验值对得起价格"],
    noticeItems: ["另收 15% 服务费，预算需多抓一成半","部分主题房如高尔夫球场需另加 500 元","服务体感因人而异，不同技师对剧本投入程度可能不同"],
    conclusion: '东方皇堡水疗是澳门唯一专注「剧本杀＋角色扮演」的桑拿会所，主题房数量、沉浸度与玩法自由度都是全澳第一。如果你去过壹号、豪门但想玩得更「刺激」更有「剧情」，东方皇堡绝对是首选。',
    coverBadge: '主题房鼻祖',
    coverBadgeEn: 'Pioneer of Themed Rooms',
    coverImage: '/venues/covers/east-castle-spa.webp',
  },

  {
    slug: 'noble-spa',
    name: '尊贵',
    nameEn: 'Noble Spa',
    tagline: '买一送一老牌，方案直观',
    taglineEn: 'The classic buy-one-get-one destination',
    tag: 'value',
    categories: ['主题房','阵容'],
    aliases: '尊贵水疗、尊贵桑拿、澳门尊贵',
    technicianCount: '70+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 免费独立关门睡房',
    paymentMethods: '现金、刷卡、微信、支付宝（免服务费）',
    bestFor: '最豪华装修／KTV派对房',
    processSteps: [
      { title: '抵达澳门半岛场馆', titleEn: '', desc: '尊贵水疗位于澳门半岛，金色与大理石贯穿全场，一踏进门便尽显顶级会所气派。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '奢华更衣区及沐浴空间，金色装饰与云石铺陈。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '免费餐饮全程供应，含招牌菜式。', descEn: '' },
      { title: '看风景模式选技师', titleEn: '', desc: '70多位技师于大厅排成靓丽的风景线，部分更会主动微笑、近距离互动，让客人从容挑选。', descEn: '' },
      { title: '十多种主题情境房', titleEn: '', desc: '空姐、护士、秘书、警察等角色扮演主题房，另设KTV派对房。', descEn: '' },
      { title: '独立关门睡房过夜', titleEn: '', desc: '免费独立关门睡房，无需与他人共用躺椅区，安睡到天光。', descEn: '' },
    ],
    price: 1480,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 4.2,
    image: '/venues/noble.jpg',
    features: ['免服务费', '房间最多', '餐饮好'],
    featuresEn: ['No Service Charge', 'Most Rooms', 'Great Dining'],
    highlights: [
      { icon: 'tag', title: '买一送一', titleEn: 'Buy 1 Get 1', desc: '老牌买一送一方案，价格直观', descEn: 'Classic BOGO offer, straightforward pricing' },
      { icon: 'shield', title: '无服务费', titleEn: 'No Service Charge', desc: '总成本控制更直观', descEn: 'More transparent total cost' },
    ],
    reviewSections: [
      { title: '方案与价格', titleEn: 'Packages & Pricing', content: '尊贵算是较早把买一送一打成招牌的店之一。买一送一最大的优点是心理上觉得有赚到，但也要注意水床可能需要加购。人员数量波动较大，多的时候70+，少的时候30左右。', contentEn: 'Noble was one of the first to make BOGO their signature. The main benefit is perceived value, though water bed access may require an add-on. Staff numbers fluctuate significantly, from 30 to 70+.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1480, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '买一送一套餐', nameEn: 'BOGO Package', price: 1680, desc: '双人买一送一方案', descEn: 'Buy one get one duo package' },
    ],
    pros: ['买一送一方案直观', '无服务费', '环境不错'],
    prosEn: ['Straightforward BOGO offer', 'No service charge', 'Good environment'],
    cons: ['人员数量波动较大', '水床需加购'],
    consEn: ['Staff numbers fluctuate', 'Water bed requires add-on'],
    suitableFor: '追求性价比、想体验双人方案的客人',
    suitableForEn: 'Those seeking value and duo package experiences',
    coverBadge: '最豪华',
    coverBadgeEn: 'Most Luxurious',
    coverImage: '/venues/covers/majesty-spa.webp',
    longDescription: '尊贵水疗被许多老司机公认为「澳门装修最奢华的桑拿」，传闻投资高达一亿元——房间、休息区、大型浴池全部重金打造，设备华丽空间宽敞。大厅采用「看风景」选秀模式，70 多位技师列队展示，部分更会主动微笑互动，让你从容挑选心仪对象。尊贵最过人之处在于过夜体验：深夜可安排免费独立关门睡房，无需与他人共用躺椅区，是全澳最适合过夜的场馆之一。免费餐饮超级丰富——牛扒、炒饭、水果、冰镇啤酒 15 小时内无限享用。另设十多种角色扮演主题房与 KTV 派对房，加上免服务费、买一送一优惠，让尊贵成为追求豪华环境与过夜首选客人的不二之选。',
    longDescriptionEn: 'Noble Spa is widely regarded as Macau\'s most luxuriously decorated sauna, rumored to have invested nearly 100 million MOP. Rooms, rest areas, and large bathing pools are all lavishly built. The "scenery-viewing" selection mode features 70+ technicians lining up in the hall, some proactively smiling and interacting. Noble\'s standout feature is overnight stays — free private rooms after midnight, making it one of the best venues for sleeping over. Complimentary dining is exceptionally generous: steak, fried rice, fresh fruit, and chilled beer for up to 15 hours. Over 10 themed role-play rooms plus a KTV party room. No service charge and buy-one-get-one offers make Noble the top choice for guests who prioritize luxury and overnight comfort.',
    serviceContent: '尊贵水疗被许多老司机公认为「澳门装修最奢华的桑拿」，传闻投资高达一亿元——房间、休息区、大型浴池全部重金打造，设备华丽、空间宽敞。采用「大厅选秀」模式，70 多位技师列队展示，部分更会主动微笑互动，让你从容挑选。最大特色是「超适合过夜」——深夜后可安排独立休息房间（非常少见），房间宽敞安静、私密度高，逗留时间长达 15 小时。免费餐饮超级丰富——牛扒、炒饭、新鲜水果、冰镇啤酒 15 小时内无限享用。恋爱房间比多数桑拿更大更精致，包含大型浴池与气氛灯光。',
    recommendReasons: ["全澳装修最奢华的桑拿之一，氛围高端、设备新颖、空间宽敞","最适合过夜的桑拿——可安排私人房间，不另收费","免费餐饮超丰富，牛扒炒饭啤酒 15 小时无限享用","价格含服务费，无额外 10% 或 15% 附加","氛围安静舒适，不想排队就选尊贵"],
    noticeItems: ["小费文化比较普遍，需注意不要让技师主动打机（可能被要求 1000），明确拒绝即可","价格属中高档定位，但相对于环境与服务，体验性价比极高","周末建议提前预约，独立睡房数量有限"],
    conclusion: '如果你追求华丽、宁静、服务细腻的桑拿体验，尊贵水疗绝对是澳门最值得前往的选择之一。特别推荐给想要过夜、不订酒店的旅客——尊贵的独立睡房与免费餐饮，是其他场馆极少能比的。',
    ranking: 7,
    gallery: [
      '/venues/noble/01.webp',
      '/venues/noble/02.webp',
      '/venues/noble/03.webp',
      '/venues/noble/04.webp',
      '/venues/noble/05.webp',
      '/venues/noble/06.webp',
      '/venues/noble/07.webp',
      '/venues/noble/08.webp',
      '/venues/noble/09.webp',
    ],
    galleryCaptions: [
      '尊贵水疗的中式囍庆主题房，金绒圆床搭配云石地板尽显奢华。',
      '尊贵水疗的金色云石泡池，水晶吊灯映照是澳门桑拿顶级浴区。',
      '尊贵水疗的医护角色扮演主题房，病床与点滴架打造独特情境体验。',
      '尊贵水疗的埃及法老主题房，金黑大床与壁画重现古埃及风情。',
      '尊贵水疗的角色扮演服装间，多款COSPLAY戏服任君挑选增添乐趣。',
      '尊贵水疗的拳击健身主题房，健身器材与红色拳套打造热血情境。',
      '尊贵水疗的豪华KTV派对房，炫彩灯光与水晶吊灯嗨唱不停。',
      '尊贵水疗的弧形木格天花走廊，云石地板倒映暖光气派非凡。',
      '尊贵水疗的金色招牌与云石拱廊大堂，尽显澳门桑拿尊荣气派。',
    ],
  },

  {
    slug: 'elite-sauna',
    name: '晋会',
    nameEn: 'Jin Hui Sauna',
    tagline: '皇堡升级版・KTV包房・赛博朋克主题',
    taglineEn: 'Upgraded Eastern Castle with KTV rooms & cyberpunk themes',
    tag: 'KTV',
    categories: ['KTV', '主题房'],
    aliases: '晋会MCLUB、澳门晋会、M Club',
    technicianCount: '60+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '14:00–06:00',
    overnight: '可过夜 — 免费休息区',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '剧本杀主题房／KTV派对／科技感体验',
    processSteps: [
      { title: '抵达场馆', titleEn: '', desc: '晋会MCLUB位于氹仔，由东方皇堡同一营运团队打造，装修更新颖、科技感更强。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '赛博朋克风格更衣区与沐浴空间，霓虹灯带营造未来科技氛围。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '免费餐饮供应，在科技感休息区享用。', descEn: '' },
      { title: '自由浏览挑选', titleEn: '', desc: '60+八国技师自由浏览，19:00后阵容最齐，风格偏皇堡气质路线。', descEn: '' },
      { title: 'KTV包房+情境主题房', titleEn: '', desc: '独家KTV包房派对模式——先唱歌喝酒暖场，再投入沉浸式主题互动。赛博朋克、星空宇宙、神奇女侠、日式温泉等主题房。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '免费休息区可过夜，氛围清幽私密。', descEn: '' },
    ],
    price: 1980,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.4,
    image: '/venues/elite.jpg',
    features: ['KTV', '共浴房', '剧本', '夜店风'],
    featuresEn: ['KTV', 'Co-bath room', 'Roleplay scripts', 'Nightclub style'],
    highlights: [
      { icon: 'music', title: 'KTV包厢', titleEn: 'KTV Rooms', desc: '商K小时制包厢，先喝先聊', descEn: 'Hourly KTV rooms, drink and chat first' },
      { icon: 'bath', title: '共浴房', titleEn: 'Co-Bath Room', desc: '日式露天温泉风格装潢', descEn: 'Japanese outdoor onsen-style decor' },
    ],
    reviewSections: [
      { title: '氛围与场景', titleEn: 'Atmosphere & Scenes', content: '晋会的人员质感偏皇堡那种气质路线，人员数量偏少但弹性大。装修偏夜店路线，风格鲜明辨识度高。有剧本、KTV、共浴房，玩法偏场景氛围型。', contentEn: 'Elite has an Orient Palace-style aesthetic quality. Staff numbers are smaller but flexible. Nightclub-style decor with high distinctiveness. Features scripts, KTV, and co-bath rooms for scene-driven experiences.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1980, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: 'KTV+体验', nameEn: 'KTV + Experience', price: 2980, desc: 'KTV包厢+完整体验', descEn: 'KTV room + full experience' },
    ],
    pros: ['人员质感高', '场景氛围独特', 'KTV/共浴/剧本多样'],
    prosEn: ['High staff quality', 'Unique scene atmosphere', 'Diverse: KTV/co-bath/scripts'],
    cons: ['人员数量偏少', '无水床'],
    consEn: ['Limited staff numbers', 'No water bed'],
    suitableFor: '喜欢幽静低调、偏奢华私密感的客人',
    suitableForEn: 'Those who prefer quiet, low-key, luxurious privacy',
    coverBadge: 'KTV主题',
    coverBadgeEn: 'KTV Themed',
    coverImage: '/venues/covers/m-club.webp',
    longDescription: '晋会是东方皇堡的升级版——同一营运团队打造，但装修更新颖、科技感更强、空间更大、氛围更沉浸。场内以赛博朋克与未来科技为基调，霓虹灯带、星空宇宙投影、金属风格墙面，一踏进门便将你带入另一个世界。超丰富的角色扮演剧本涵盖星空宇宙房、神奇女侠、桌球女郎、日式温泉泡泡浴、SM 专属房、女仆、OL 办公室、警察与嫌犯等，每个房间都有不同的氛围、服装与互动方式，玩法比一般桑拿更立体。最迷人之处是独家 KTV 包房派对模式——全澳仅有的桑拿 KTV，可以先唱歌喝酒暖场再投入沉浸式主题互动，非常适合多人同行。8 国 60+ 技师自由浏览，19:00 后阵容最齐，与皇堡共用技师资源，素质、服务、互动方式皆属高水准。加收一成五服务费。',
    longDescriptionEn: 'Elite Sauna is the upgraded version of Orient Palace — same team, newer decor, stronger tech vibe, larger space, deeper immersion. Cyberpunk and futuristic styling with neon strips, starry sky projections, and metallic walls. Rich role-play scripts: cosmos room, Wonder Woman, billiard girl, Japanese onsen bubble bath, SM room, maid, OL office, cop & suspect, and more — each room has unique atmosphere, costumes, and interaction. The standout: exclusive KTV party rooms — the only sauna in Macau with KTV, perfect for groups to sing and drink before immersive themed sessions. 60+ technicians from 8 countries, fullest lineup after 19:00, shared talent pool with Orient Palace for consistently high quality. 15% service charge.',
    serviceContent: '晋会 M Club 位于澳门华都酒店，邻近外港码头与多家娱乐场，是东方皇堡的升级版——同一营运团队打造，但装修更新颖、科技感更强、空间更大、氛围更沉浸。主打「主题房间＋剧本杀式互动」，包含星空宇宙房、神奇女侠、桌球女郎、日式温泉泡泡浴、SM 专属房、女仆、OL 办公室、警察与嫌犯等多种自选剧本，每个房间有不同的氛围、服装与互动方式。独有 KTV 包房——可以唱歌喝酒派对，再进行房间体验，是全澳唯一选择。与皇堡共用技师资源，素质、服务、互动方式皆属高水准。另收 15% 服务费。',
    recommendReasons: ["沉浸式主题房体验比皇堡更高级——装修更新颖、科技感更强、空间更大","皇堡姐妹店，技师共用，素质等级完全一致","全澳唯一拥有 KTV 主题包房的桑拿——唱歌喝酒派对再体验","多元主题与超多服装，玩法比一般桑拿更立体更沉浸","赛博朋克风格装修，适合喜欢新鲜感与科技感的玩家"],
    noticeItems: ["另收 15% 服务费，整体价格比皇堡平均贵约 400 澳门币","部分主题房需额外费用","营业时间为 14:00–06:00，非 24 小时营业","KTV 包房建议提前预约，避免满房"],
    conclusion: '晋会的定位非常明确：更豪华、更科技、更沉浸、更私密。如果皇堡是剧本杀的起源，那么晋会就是剧本杀的升级版。想玩剧本杀、想唱歌派对、想要比皇堡更高档的环境——晋会是全澳唯一选择。',
    ranking: 8,
    suspended: true,
    gallery: [
      '/venues/elite/01.webp',
      '/venues/elite/02.webp',
      '/venues/elite/03.webp',
      '/venues/elite/04.webp',
      '/venues/elite/05.webp',
      '/venues/elite/06.webp',
      '/venues/elite/07.webp',
      '/venues/elite/08.webp',
      '/venues/elite/09.webp',
      '/venues/elite/10.webp',
      '/venues/elite/11.webp',
      '/venues/elite/12.webp',
      '/venues/elite/13.webp',
      '/venues/elite/14.webp',
      '/venues/elite/15.webp',
    ],
    galleryCaptions: [
      '晋会MCLUB的运动赛事休息室配备多面大萤幕与霓虹光条，尽显科技感豪华风格。',
      '晋会MCLUB的日式温泉主题池以枫红森林投影环绕，营造静谧泡汤氛围。',
      '晋会MCLUB的极光星空主题房设有发光按摩浴池，沉浸于梦幻北极光之中。',
      '晋会MCLUB的豪华KTV包厢以红蓝霓虹与星河投影打造未来感欢唱空间。',
      '晋会MCLUB的环幕KTV包厢以雪山投影与蓝光大理石地板营造科技氛围。',
      '晋会MCLUB的撞球主题套房结合美式撞球桌、酒柜与时光隧道壁画设计。',
      '晋会MCLUB的高尔夫主题房铺设果岭草坪并停放高球车，重现绿地球场情境。',
      '晋会MCLUB的赛车模拟主题房配备双人赛车座椅与互动投影对战萤幕。',
      '晋会MCLUB的飞镖游戏厅以紫色霓虹光带与圆凳座椅打造夜店感娱乐空间。',
      '晋会MCLUB的榻榻米主题房以原木暖光卧榻与镜面设计营造温馨日式格调。',
      '晋会MCLUB的角色扮演主题房备有威尼斯面具与蜡烛，增添神秘情调氛围。',
      '晋会MCLUB的红色角色扮演主题房以绒幕与精致道具柜营造神秘情境氛围。',
      '晋会MCLUB的更衣置物区铺设金纹大理石地板并设紫色绒凳，尽显奢华质感。',
      '晋会MCLUB的主题房走廊以紫蓝霓虹线条与M字标志引导通往各主题包厢。',
      '晋会MCLUB的镜面大堂以紫光招牌与M字标志迎宾，展现科技感入口门面。',
    ],
  },

  {
    slug: 'mansion-sauna',
    name: '豪门',
    nameEn: 'Mansion Sauna',
    tagline: '澳门最大场馆、房间最多、性价比最高',
    taglineEn: 'Freedom of choice at your own pace',
    tag: 'hot',
    categories: ['阵容'],
    aliases: '豪门桑拿殿、豪门水疗、澳门豪门',
    technicianCount: '80+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 全澳最佳过夜设施',
    paymentMethods: '现金、刷卡、微信、支付宝（免服务费）',
    bestFor: '全澳场馆最大房间最多／免服务费性价比最高',
    processSteps: [
      { title: '抵达澳门半岛场馆', titleEn: '', desc: '豪门桑拿殿位于澳门半岛，规模为全澳最大。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '宽敞沐浴空间，干湿蒸房一应俱全。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '口碑极佳的免费牛排与冻啤，全程无限量供应。', descEn: '' },
      { title: '大厅选秀', titleEn: '', desc: '18:00后切换大厅选秀模式，80多位技师近距离挑选。', descEn: '' },
      { title: '独立房间服务', titleEn: '', desc: '房间数量全澳之最，高峰时段也几乎无需等候。', descEn: '' },
      { title: '全澳最佳过夜', titleEn: '', desc: '躺椅数量最多、间距最宽，休息区安静无嘈杂，过夜舒适自在。', descEn: '' },
    ],
    price: 1380,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.5,
    image: '/venues/haomen/01.jpg',
    gallery: [
      '/venues/mansion/01.webp',
      '/venues/mansion/02.webp',
      '/venues/mansion/03.webp',
      '/venues/mansion/04.webp',
      '/venues/mansion/05.webp',
      '/venues/mansion/06.webp',
      '/venues/mansion/07.webp',
      '/venues/mansion/08.webp',
      '/venues/mansion/09.webp',
      '/venues/mansion/10.webp',
      '/venues/mansion/11.webp',
      '/venues/mansion/12.webp',
    ],
    videos: [
      '/venues/haomen/video01.mp4',
      '/venues/haomen/video02.mp4',
      '/venues/haomen/video03.mp4',
    ],
    features: ['自由选秀', '韩国路线', '性价比'],
    featuresEn: ['Free selection', 'Korean lineup', 'Value'],
    highlights: [
      { icon: 'eye', title: '自由挑选', titleEn: 'Free Selection', desc: '走廊移动、边看边选，自己掌控节奏', descEn: 'Walk the hallway, browse and choose at your pace' },
      { icon: 'flag', title: '韩国路线', titleEn: 'Korean Lineup', desc: '韩国路线表现不错，有存在感', descEn: 'Strong Korean lineup with notable presence' },
    ],
    reviewSections: [
      { title: '选秀方式', titleEn: 'Selection Style', content: '豪门的挑选方式更自由，不用等一轮一轮出场，更像自己掌控节奏。适合对选秀效率、自由度要求高的人。', contentEn: 'Mansion offers a more free-form selection style. No waiting for batch presentations — you control your own pace. Great for those who value efficiency and freedom.' },
      { title: '人员路线', titleEn: 'Staff Lineup', content: '韩国路线表现不错，东南亚也还行。国人比例相对较低，节假日期人员波动更小，适合避开热门店拥挤。', contentEn: 'Strong Korean lineup with decent Southeast Asian options. Lower domestic staff ratio means less holiday fluctuation, ideal for avoiding crowded top venues.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1380, desc: '单人基础服务', descEn: 'Standard single service' },
    ],
    pros: ['挑选方式自由高效', '韩国路线表现好', '节假日期稳定'],
    prosEn: ['Free and efficient selection', 'Strong Korean lineup', 'Stable during holidays'],
    cons: ['人员数量不如壹号帝湖', '平均颜值一般'],
    consEn: ['Fewer staff than top venues', 'Average aesthetics level'],
    suitableFor: '喜欢自己掌控挑选节奏、在意效率的客人',
    suitableForEn: 'Those who prefer controlling their own selection pace',
    ranking: 10,
    suspended: true,
    longDescription: '豪门桑拿长年稳坐「澳门最大桑拿场馆」的地位，房间数量全澳之最——即使在高峰时段，一踏进门便有房可进，几乎无需等候，有效避免壹号那样动辄排房一两小时的情况。每日 80 多位来自八个国家的技师任你选择，采用经典「看风景选秀」模式：18 点前由经理安排一排技师站在面前近距离挑选，18 点后所有技师在大厅排队走秀、轻微互动。豪门最核心的竞争力是性价比——全澳仅两家免服务费，标价即最终价，没有隐藏收费。管理完善，不会乱收小费。越南妹服务最贴心、大陆妹颜值稳定沟通顺、日韩系是男性梦幻选择、俄乌欧式品质在线。免费牛排与冻啤口碑极佳，过夜休息区躺椅数量最多、间距宽敞，安静舒适。推荐指数五星，是许多人初次体验澳门桑拿的首选，也是过夜与精打细算者的理想之选。',
    longDescriptionEn: 'The price you see is the price you pay — Mansion Sauna is one of only two venues in Macau with explicitly no service charge. Scale-wise, it\'s the largest sauna venue in Macau with the most rooms, completely avoiding peak-hour waits. 80+ technicians from 8 nationalities (CN, VN, TH, TW, JP, KR, RU, UA), with lobby selection mode after 18:00. Pricing from MOP 2,388–6,988, 24-hour operation with Macau\'s best overnight facilities — the most recliners with widest spacing, a first stop for many Macau sauna visitors.',
    serviceContent: '豪门桑拿长年稳坐「澳门最大桑拿场馆」的地位，房间数量全澳之最——即使在高峰时段，一踏进门便有房可进，有效避免壹号桑拿那样动辄排队等房的情况。采用经典「看风景选秀」模式：18:00 前由经理安排一排技师站列近距离挑选，18:00 后所有上班技师在大厅排队走秀，经理提前告知「编号区间」对应的价格。每日 80+ 美女，阵容涵盖中国、越南、泰国、台湾、日韩、俄罗斯、乌克兰。自 2025 年 1 月起全面免服务费，在澳门众多桑拿中属非常高性价比。',
    recommendReasons: ["场馆最大、房间最多，几乎不用排队","自 2025 年 1 月起免服务费，性价比极高","每日 80+ 技师，菜系最齐全，不怕挑不到心仪的","管理完善，服务员态度佳，不会乱收小费","位于市中心，交通便利，免费餐饮质素不错（尤其牛扒）"],
    noticeItems: ["少数极度爆场的周末除外，高峰时段仍可能需要短暂等候","越南技师部分不会中文，需要翻译器辅助沟通","日韩系价格较高（5988–6588），偶尔有知名女优等级"],
    conclusion: '豪门桑拿是非常适合第一次来澳门体验桑拿的人——场馆大、房间多、不用排队、免服务费、技师选择丰富。稳定、安全、性价比高，是澳门桑拿的「入门首选」。',
    coverBadge: '免服务费',
    coverBadgeEn: 'No Service Charge',
    coverImage: '/venues/covers/haomen-sauna.webp',
  },

  {
    slug: 'number-one-sauna',
    name: '壹号',
    nameEn: 'Number One Sauna',
    tagline: '连续多年稳居澳门最热门桑拿，技师数量全澳之最',
    taglineEn: 'The heavyweight champion of selection',
    tag: 'hot',
    categories: ['阵容'],
    aliases: '壹号桑拿、壹号水疗、澳门壹号',
    technicianCount: '130+ 位技师',
    technicianTeam: '中、日、韩、台、越、泰、蒙、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 免费躺椅休息区',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '连续多年稳居澳门最热门／水床莞式选秀',
    bestForEn: 'Most popular in Macau / Water bed show',
    processSteps: [
      { title: '抵达御龙酒店', titleEn: '', desc: '壹号桑拿位于澳门半岛御龙酒店，从关闸约10分钟车程即达。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '宽敞更衣室及大型按摩浴池，干湿蒸房一应俱全。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '招牌牛排与多国餐饮全程无限量供应。', descEn: '' },
      { title: '动态走秀选技师', titleEn: '', desc: '分批沿大厅展示的动态走秀，场面壮观、选择丰富，是先观赏再从容挑选的独特体验。', descEn: '' },
      { title: '独立房间服务', titleEn: '', desc: '进入独立房间享受一对一专属服务，全程私密无干扰。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '休息区躺椅可供小憩或直接过夜，想留多久都可以。', descEn: '' },
    ],
    price: 1780,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 4.8,
    image: '/venues/number-one.jpg',
    features: ['东南亚', '双人服务', '高颜值', '装修质感'],
    featuresEn: ['Southeast Asian', 'Duo service', 'High aesthetics', 'Quality interior'],
    highlights: [
      { icon: 'crown', title: '量级王者', titleEn: 'Selection King', desc: '就可选数量来看，依然是第一梯队', descEn: 'Still the top tier in terms of selection quantity' },
      { icon: 'sparkles', title: '高颜值水准', titleEn: 'High Aesthetics', desc: '整体颜值水准高，偏看中外在与氛围', descEn: 'High overall aesthetics, focused on visual appeal' },
      { icon: 'star', title: '服务稳定', titleEn: 'Stable Service', desc: '综合服务表现稳定、体验完成度高', descEn: 'Consistent service with high completion quality' },
    ],
    reviewSections: [
      { title: '人员与类型', titleEn: 'Staff & Types', content: '壹号依然是第一梯队，东南亚风格相对更强，国人路线也不差，类型齐全选择面广。人员数量多、风格分布多元，能满足不同偏好。', contentEn: 'Number One remains in the top tier. Strong Southeast Asian lineup, solid domestic options, and broad selection across all categories.' },
      { title: '环境氛围', titleEn: 'Atmosphere', content: '装修氛围有质感，场子看起来有料，门面感较好。双人服务价格在同类型中相对友善。', contentEn: 'Quality interior with impressive presentation and strong curb appeal. Duo service pricing is relatively friendly.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1780, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '双人套餐', nameEn: 'Duo Package', price: 2780, desc: '双人互动体验', descEn: 'Interactive duo experience' },
    ],
    pros: ['人员数量多、类型齐全', '整体颜值水准高', '双人服务价格友好'],
    prosEn: ['Large and diverse staff selection', 'High overall aesthetics', 'Duo service pricing is friendly'],
    cons: ['热门时段可能排队', '选秀区光线偏暗'],
    consEn: ['Peak hours may require queuing', 'Selection area lighting is dim'],
    suitableFor: '看重颜值、服务体感、可选数量的客人',
    suitableForEn: 'Those who value aesthetics, service quality, and selection',
    ranking: 11,
    suspended: true,
    longDescription: '连续多年稳居澳门最热门的桑拿房，壹号桑拿人气之所以咁高，最大原因是全澳最多元、最齐全嘅技师阵容——常驻超过 140 位技师，涵盖中、越、泰、日、韩、俄、乌克兰等多国风情，甜美型、火辣型、高冷型、御姐型一应俱全。中国模特阵容最强，甚至有机会遇见抖音或小红书上关注的网红美女。每晚约 18:30 开始的「水床莞式选秀」是壹号的招牌——超过一百位技师在宽敞秀场中缓缓登场，气氛热烈到爆，被许多老饕称为「澳门最美的风景」。看到喜欢的，向经理示意即可安排。壹号同时提供人气极高的「双妃服务」，仅需 MOP 1,000 追加一位越南技师加入，互动更多元。2023 年全面翻新装修，大厅气派、各式房间风格现代。场馆 24 小时营业、可停留最长 15 小时、可过夜，免费牛排与多国餐饮全程供应。由于人气极高，周末高峰时段经常排队等房 1–2 小时，建议提前预约，或改去豪门桑拿、尊贵水疗同属高端会所。',
    longDescriptionEn: 'Looking for the venue with the most technicians in Macau? Number One Sauna is the answer. With a total roster of 130+ and about 100+ multi-national technicians on shift daily, dynamic selection rounds ensure even the pickiest visitors rarely leave empty-handed. A perennial favorite, it features a complete and consistent lineup from 8 countries, with particularly strong Taiwanese representation and professional-grade selection shows. Price range approximately MOP 2,199–7,699, 24-hour operation, overnight stays available, free signature steak and multi-national cuisine throughout. About 10 minutes from the Border Gate; the venue is not large, so queuing during peak hours is common.',
    serviceContent: '壹号桑拿采用极具视觉冲击力的「水床莞式选秀」模式——每晚约 18:30 开始，超过一百位来自各地的美女技师在宽敞秀场中缓缓登场，气氛热烈壮观。技师数量为全澳之最，阵容涵盖中国、越南、泰国、日本、韩国、俄罗斯等，类型多元——甜美型、火辣型、高冷型一应俱全。招牌「双妃服务」仅需 MOP 1,000 追加即可安排一位越南技师加入，互动更多元、氛围更热烈，是熟客口碑最好的加值服务之一。2023 年全面翻新装修，大厅气派宽敞，水床、蒸气房、按摩池等设备全面升级。',
    recommendReasons: ["连续多年稳居澳门最热门桑拿，技师数量全澳之最——常驻 140+ 位技师，选择面无可匹敌","「水床莞式选秀」是澳门桑拿文化的代表场面，每晚走秀气氛震撼","整体设施、管理与服务流程完善，环境高级、干净、舒适","双妃服务仅 MOP 1,000 追加，性价比极高","中国模特阵容最强，甚至有机会遇见网红美女"],
    noticeItems: ["周末及假期晚市时段（10–12 点）经常需要排队等房，有时等待超过 1 小时，建议提前预约","平日下午 3 点至 6 点前人流相对少，拣人更从容；夜晚 9 点后则是「黄金秀场时间」","人气极高意味着高峰时段服务可能因人而异，需要合理管理期望"],
    conclusion: '壹号桑拿的「水床莞式选秀」不仅是视觉飨宴，更是澳门桑拿文化的代表。无论是技师数量、场馆规模还是整体服务，壹号都堪称澳门最顶级、最具代表性的桑拿之一。若想体验震撼的大场面与精致服务，这里绝对是首选。',
    coverBadge: '最热门',
    coverBadgeEn: 'Best Lineup',
    coverImage: '/venues/covers/number-one-sauna.webp',
    gallery: [
      '/venues/numberone/01.webp',
      '/venues/numberone/02.webp',
      '/venues/numberone/03.webp',
      '/venues/numberone/04.webp',
      '/venues/numberone/05.webp',
      '/venues/numberone/06.webp',
      '/venues/numberone/07.webp',
      '/venues/numberone/08.webp',
      '/venues/numberone/09.webp',
      '/venues/numberone/10.webp',
      '/venues/numberone/11.webp',
      '/venues/numberone/12.webp',
    ],
    galleryCaptions: [
      '壹号桑拿挑高大堂以花卉地毯与发光玉石柜台迎宾，气势十足。',
      '壹号桑拿大理石墙上的发光金字招牌，是澳门桑拿的醒目地标。',
      '壹号桑拿的私人休息包厢，红色皮革卡座搭配花卉艺术墙与旋纹地毯，安静雅致。',
      '壹号桑拿炫彩发光座椅围出的休闲角落，营造澳门桑拿的时尚氛围。',
      '壹号桑拿以流线地毯与卡座打造的雅致休息区，让宾客尽情放松。',
      '壹号桑拿更衣置物长廊两侧排列坐凳，动线宽敞舒适。',
      '壹号桑拿盥洗梳妆区点缀竹景与石材台面，细节精致。',
      '壹号桑拿室内浴池水区灯光柔和，提供舒缓的澳门桑拿泡浴体验。',
      '壹号桑拿按摩理疗房备有金色疗床与木桶，提供专业细致服务。',
      '壹号桑拿高级理疗套房以大理石铺陈，营造尊享私密环境。',
      '壹号桑拿私人睡房配置双人床与木质地板，适合过夜休息。',
      '壹号桑拿招牌免费餐饮满桌，招牌牛排与多样热菜任你享用。',
    ],
  },

  {
    slug: 'imperial-spa',
    name: '帝湖',
    nameEn: 'Imperial Spa',
    tagline: '氹仔新区最具人气的高端桑拿，双妃全澳最优惠',
    taglineEn: 'Well-staffed with excellent dining',
    tag: 'hot',
    categories: ['阵容'],
    aliases: '帝湖桑拿、帝湖水疗、澳门帝湖',
    technicianCount: '140+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 免费躺椅休息区',
    paymentMethods: '现金、刷卡、微信、支付宝（另加10%服务费）',
    bestFor: '氹仔新区最具人气／日韩技师最多',
    processSteps: [
      { title: '抵达氹仔场馆', titleEn: '', desc: '帝湖桑拿位于氹仔，紧邻路氹城各大酒店，是行程有限的旅客最省力的选择。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '宽敞沐浴区，干湿蒸房及大型按摩浴池。', descEn: '' },
      { title: '免费海鲜自助', titleEn: '', desc: '下午5至8时供应免费海鲜自助餐，虾、蟹、贝类、三文鱼刺身一应俱全。', descEn: '' },
      { title: '展览式走秀', titleEn: '', desc: '技师由入口依序走上中央舞台，外型、身材与仪态逐一亮相，让你从容合眼缘。', descEn: '' },
      { title: '主题房服务', titleEn: '', desc: '多款古典主题房，进入独立房间享受一对一专属服务。', descEn: '' },
      { title: '休息区过夜', titleEn: '', desc: '宽敞的过夜休息区，躺椅舒适安静。', descEn: '' },
    ],
    price: 1680,
    currency: 'MOP',
    area: '氹仔',
    areaEn: 'Taipa',
    rating: 4.7,
    image: '/venues/imperial/01.jpg',
    gallery: [
      '/venues/imperial/01.webp',
      '/venues/imperial/02.webp',
      '/venues/imperial/03.webp',
      '/venues/imperial/04.webp',
      '/venues/imperial/05.webp',
      '/venues/imperial/06.webp',
      '/venues/imperial/07.webp',
      '/venues/imperial/08.webp',
      '/venues/imperial/09.webp',
      '/venues/imperial/10.webp',
      '/venues/imperial/11.webp',
      '/venues/imperial/12.webp',
    ],
    galleryCaptions: [
      '帝湖桑拿的双人服务房以暖色氛围灯与护墙板打造，私密舒适。',
      '帝湖桑拿设有展览式选秀舞台与弧形座椅，方便客人现场挑选技师。',
      '帝湖桑拿的排椅休息区整齐配备个人萤幕，可边歇息边享受服务。',
      '帝湖桑拿的日式主题房以木格天花与大理石浴池，营造温泉雅致氛围。',
      '帝湖桑拿的水区设有金色天花、双浴池与玻璃蒸气桑拿房，奢华大气。',
      '帝湖桑拿水区一隅设有蓝砖浴池吧台与休息躺椅，动线宽敞自在。',
      '帝湖桑拿的高级睡房配软包床头与镜墙设计，沉稳典雅好放松。',
      '帝湖桑拿的豪华套房以水晶吊灯、雕花天花与独立沙发区尽显气派。',
      '帝湖桑拿海鲜自助餐供应船形刺身拼盘，三文鱼、吞拿与鲜虾丰盛上桌。',
      '帝湖桑拿海鲜自助餐热菜台有椒盐虾、膏蟹与烧牛扒，荤腥俱全。',
      '帝湖桑拿海鲜自助餐另备白灼鲜虾、花甲与海鲜冷盘，食材新鲜多元。',
      '帝湖桑拿位于氹仔路氹城一带，大楼金光夜景外观醒目、交通便利。',
    ],
    videos: [
      '/venues/imperial/video01.mp4',
      '/venues/imperial/video02.mp4',
    ],
    features: ['水床', '双人服务', '餐饮', '过夜'],
    featuresEn: ['Water bed', 'Duo service', 'Dining', 'Overnight'],
    highlights: [
      { icon: 'users', title: '人员充足', titleEn: 'Well-Staffed', desc: '可选空间相对充足，风格多元', descEn: 'Ample selection with diverse styles' },
      { icon: 'utensils', title: '餐饮强项', titleEn: 'Great Dining', desc: '餐饮口碑稳定，整体水准在线', descEn: 'Consistently good dining experience' },
      { icon: 'bed', title: '房间舒适', titleEn: 'Comfortable Rooms', desc: '房间尺度普遍偏大，使用空间舒服', descEn: 'Spacious rooms with comfortable layout' },
    ],
    reviewSections: [
      { title: '人员与选择', titleEn: 'Staff & Selection', content: '帝湖主打人员配置量足，现场通常会分批次出场，对想慢慢挑选的人来说可选空间是够的。服务人员风格多元，能满足不同偏好。', contentEn: 'Imperial Spa is known for its well-staffed lineup. Staff are presented in batches, giving you ample time to choose. Diverse styles to match various preferences.' },
      { title: '环境与硬体', titleEn: 'Environment & Facilities', content: '公共区域装修偏成熟风格，但房间尺度普遍偏大、使用空间舒服，整体体验被拉回不少。', contentEn: 'Common areas have a mature aesthetic, but rooms are notably spacious and comfortable, enhancing the overall experience.' },
      { title: '餐饮表现', titleEn: 'Dining Quality', content: '帝湖的餐饮一直是被反复提到的优势，整体水准在线，算是它能长期维持好感度的原因之一。', contentEn: 'Dining is a frequently mentioned strength, consistently high quality, and a key reason for its sustained positive reputation.' },
    ],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic Package', price: 1680, desc: '单人基础服务', descEn: 'Standard single service' },
      { name: '双人套餐', nameEn: 'Duo Package', price: 2680, desc: '双人互动体验', descEn: 'Interactive duo experience' },
      { name: 'VIP套餐', nameEn: 'VIP Package', price: 3680, desc: '尊享私密空间与加值服务', descEn: 'Premium private room with add-ons' },
    ],
    pros: ['人员数量多、类型齐全', '餐饮水准在线', '房间空间大、舒适度高'],
    prosEn: ['Large and diverse staff selection', 'Consistently good dining', 'Spacious and comfortable rooms'],
    cons: ['氹仔位置稍远', '装修偏成熟风格'],
    consEn: ['Taipa location slightly remote', 'Mature interior style'],
    suitableFor: '追求可选数量、整体状态与体验稳定度的客人',
    suitableForEn: 'Those seeking variety, consistent quality, and stable experiences',
    ranking: 12,
    suspended: true,
    longDescription: '帝湖水疗是氹仔新区核心地段最受欢迎的高端桑拿，紧邻美狮美高梅、银河度假村、永利皇宫、上葡京等大型娱乐场，住氹仔的客人无需跨桥往返澳门半岛。帝湖以「高颜值阵容＋顶级服务＋全澳最优惠双妃」著称——日韩技师密度全澳最高，十多位稳定在班，被许多玩家评为全澳最稳定、最专业。招牌「展览式选秀」让技师由入口依序走上中央舞台，外型、身材与仪态逐一展示，每天大约 60 位以上技师上班。最大亮点是全澳最便宜的双妃：第二位只需第一位的 30%，越南更低至 20%——若喜欢双妃玩法，帝湖绝对是最划算的选择。下午 5 点到 8 点供应免费海鲜自助餐。颜值把关严格，每位技师都经过面试培训，踩雷机率低。另加一成服务费。',
    longDescriptionEn: 'No border crossing needed — Oceanic Royal Spa sits right in Taipa, adjacent to Cotai Strip hotels, making it the most effortless choice for time-limited travelers. As one of Taipa\'s three classic venues, it features a 140+ strong multi-national technician roster (CN/VN/TH/TW/JP/KR/RU/UA), with Japanese and Korean representation among Macau\'s best. The signature "exhibition-style selection" has technicians walking the central stage one by one, letting you take your time to find your match. Free seafood buffet from 5-8 PM with shrimp, crab, shellfish, salmon sashimi and geoduck. Price range approximately MOP 2,299–7,099 plus 10% service charge. Booking includes free entry, free transfers, and complimentary add-on services.',
    serviceContent: '帝湖水疗是氹仔新区核心地段最受欢迎的高端桑拿，紧邻美狮美高梅、银河度假村、永利皇宫、上葡京等大型娱乐场。采用「展览式选秀模式」——美女由入口依序走上中央舞台展示外型、身材与仪态，每天 60+ 技师上班。最大亮点是日韩技师密度全澳最高（十多人），颜值普遍偏高、风格多元。帝湖更是「双妃」最优惠——第二位只需第一位的 30%，越南更低至 20%，全澳最划算。晚上 7 点后每 30 分钟一轮舞台选秀，白天则由经理带一排技师站列供挑选。',
    recommendReasons: ["日韩技师密度全澳最高——十多人，品质稳定、颜值高","双妃全澳最优惠——第二位只需 30%，越南更低至 20%","氹仔核心地段，住新区不用跨桥，步行或快速抵达","颜值把关严格，每位技师都经面试培训，踩雷机率低","选秀体验强——舞台大、灯光明亮、距离适中，挑选更准确"],
    noticeItems: ["另收 10% 服务费","规模不如壹号、豪门宽敞，但「精致」是强项","价格以每日实际为准，澳门价格时常浮动","休息区按摩技师质素极高，但多半是清牌"],
    conclusion: '帝湖水疗是目前氹仔区最受欢迎的高端桑拿之一——日韩技师最多、双妃最优惠、颜值高、地点方便。无论你是第一次玩澳门桑拿，还是老司机，帝湖都是必访场馆。',
    coverBadge: '氹仔首选',
    coverBadgeEn: 'Top Taipa Pick',
    coverImage: '/venues/covers/oceanic-royal-spa.webp',
  },

  {
    slug: 'victoria-sauna',
    name: '凯旋',
    nameEn: 'Victoria Sauna',
    tagline: '安静首选，专注细致服务，澳门隐藏宝石',
    taglineEn: 'The quietest hidden gem in Macau',
    tag: 'value',
    ranking: 9,
    categories: ['高性价'],
    aliases: '凯旋桑拿、凯旋水疗、澳门凯旋',
    technicianCount: '70+ 位技师',
    technicianTeam: '中、越、泰、台、日、韩、俄、乌',
    hours: '24小时',
    overnight: '可过夜 — 凌晨3:00后免费独立睡房',
    paymentMethods: '现金、刷卡、微信、支付宝',
    bestFor: '全澳最安静／隐藏宝石',
    processSteps: [
      { title: '抵达澳门半岛场馆', titleEn: '', desc: '凯旋桑拿位于澳门半岛核心，低调简约，是知情者才懂的隐藏宝石。', descEn: '' },
      { title: '更衣与沐浴', titleEn: '', desc: '大浴场与桑拿空间都格外宽敞，让人安心放松身心。', descEn: '' },
      { title: '免费餐饮', titleEn: '', desc: '鲍鱼、鹅掌花胶、川菜、牛仔骨到甜品全程供应，餐区安静得能让你慢慢享用。', descEn: '' },
      { title: '经理面选技师', titleEn: '', desc: '这里不做走秀也没有制式选秀，把喜好交给经理直接面对面挑选，是全澳最从容的配对方式。', descEn: '' },
      { title: '私密房间服务', titleEn: '', desc: '进入独立房间享受一对一专属服务，氛围简约低调。', descEn: '' },
      { title: '独立睡房过夜', titleEn: '', desc: '与尚品、尊贵并列仅三家提供凌晨3:00后免费独立睡房的场馆，独享私人房安稳补眠。', descEn: '' },
    ],
    price: 2298,
    currency: 'MOP',
    area: '澳门半岛',
    areaEn: 'Macau Peninsula',
    rating: 4,
    image: '/venues/kaixuan/01.webp',
    gallery: [
      '/venues/kaixuan/01.webp','/venues/kaixuan/02.webp','/venues/kaixuan/03.webp',
      '/venues/kaixuan/04.webp','/venues/kaixuan/05.webp','/venues/kaixuan/06.webp',
      '/venues/kaixuan/07.webp','/venues/kaixuan/08.webp','/venues/kaixuan/09.webp',
    ],
    galleryCaptions: [
      '凯旋桑拿的多彩LED地坪大厅，环形舞台灯光点缀、后方设浸池，气派开阔。',
      '凯旋桑拿宽敞大浴场设有多座按摩池，马赛克墙面搭配温润灯光十分舒适。',
      '凯旋桑拿提供独立睡房，舒适大床与专属浴缸让你免费过夜安心休息。',
      '凯旋桑拿宁静的躺椅休息区，成排电动沙发附电视，最适合放空小睡。',
      '凯旋桑拿安静的休息躺椅区，地毯与柔和灯光打造低调私密的休憩角落。',
      '凯旋桑拿挑高的大型空间，几何灯饰与光亮地板呈现开阔气派的格局。',
      '凯旋桑拿木质更衣置物区宽敞整洁，备品床上备有干净毛巾随手可取。',
      '凯旋桑拿以大理石与金色灯光打造迎宾大厅，入口低调隐密不张扬。',
      '凯旋桑拿坐落于气派大楼内，夜晚灯火通明，是澳门低调隐密的桑拿选择。',
    ],
    features: ['24小时营业', '免费独立过夜房', '水床买一送一', '八国技师'],
    featuresEn: ['24hr Operation', 'Free Private Overnight Room', 'Water Bed BOGO', '8-Nationality Techs'],
    highlights: [
      { icon: 'shield', title: '服务细致稳定', titleEn: 'Meticulous Service', desc: '品质稳定口碑好', descEn: 'Stable quality reputation' },
      { icon: 'moon', title: '环境安静私密', titleEn: 'Quiet & Private', desc: '全澳最安静的隐藏宝石', descEn: 'Quietest hidden gem' },
      { icon: 'bed', title: '过夜首选', titleEn: 'Best for Overnight', desc: '免费独立睡房', descEn: 'Free private sleep room' },
    ],
    reviewSections: [],
    pricing: [
      { name: '基础套餐', nameEn: 'Basic', price: 2298, desc: '基础服务', descEn: 'Basic service' },
      { name: '高级套餐', nameEn: 'Premium', price: 4598, desc: '高级服务', descEn: 'Premium service' },
      { name: 'VIP套餐', nameEn: 'VIP', price: 6998, desc: 'VIP服务', descEn: 'VIP service' },
    ],
    pros: ['全澳最安静', '水床买一送一', '免费独立过夜房', '70+技师八国阵容'],
    prosEn: ['Quietest in Macau', 'Water bed BOGO', 'Free private overnight room', '70+ technicians 8 nationalities'],
    cons: ['低调不张扬', '无大型走秀'],
    consEn: ['Low key', 'No grand show'],
    suitableFor: '台湾商务出差客首选・最安静私密',
    suitableForEn: 'Best for business travelers seeking quiet & privacy',
    coverBadge: '最安静',
    coverBadgeEn: 'Quietest',
    coverImage: '/venues/covers/victoria-sauna.webp',
    longDescription: '凯旋桑拿位于澳门凯旋门酒店五楼，紧邻美高梅、永利与新葡京，是玩家圈公认「全澳最安静」的隐藏宝石。与其他场馆的走秀模式不同，凯旋不做制式选秀，而是让客人向经理直接面选技师——从容、私密、零压力。70 多位技师涵盖中、越、泰、台、日、韩、俄、乌八国，特别是日韩技师颜值与服务水准极高。免费餐饮是全澳最大方之一：鲍鱼、鹅掌花胶、川菜、牛仔骨到甜品全程供应。凌晨 3 点后可免费安排独立睡房过夜，与尚品、尊贵并列仅三家提供此福利的场馆。加收一成服务费，但整体性价比远高于壹号、十八等热门场——想避开人潮、安静放松，凯旋是首选。',
    longDescriptionEn: 'Victoria Sauna, perched on the 5th floor of the MGM-style Victoria Hotel, is Macau\'s quietest hidden gem. No runway shows — instead, a manager-led private selection from 70+ technicians across 8 nationalities, with standout Japanese and Korean talent. Complimentary gourmet dining (abalone, Sichuan cuisine, desserts) is among the most generous in Macau. After 3 AM, enjoy a free private sleep room — one of only three venues offering this perk. 10% service charge, but far better value than busier venues. Perfect for those who prefer peace, privacy, and quality.',
    serviceContent: '凯旋桑拿位于澳门凯旋门酒店五楼，紧邻美高梅、永利与新葡京，是玩家圈公认「全澳最安静」的隐藏宝石。不设固定选秀表演时间，而是让顾客自由挑选技师——到场后向经理表示，便可从眼前的技师中挑选喜欢的。技师来自越南、大陆、台湾、日本、韩国、俄罗斯、乌克兰，特别是日本和韩国技师颜值与服务水准极高。价格相对壹号、豪门更具性价比，双妃服务尤其优惠。凌晨 3 点后可安排独立睡房，不另收费。',
    recommendReasons: ["安静舒适的环境——与壹号、豪门的喧闹完全不同，宁静私密","日韩技师颜值与服务水准极高，适合追求高端体验的顾客","价格比壹号、豪门更具性价比，双妃服务尤其优惠","凌晨 3 点后免费独立睡房，过夜首选之一","位于市中心凯旋门酒店，交通便利"],
    noticeItems: ["另收 15% 服务费，预算需多抓一成半","技师数量 50+ 左右，选择面不及大场","不设走秀表演，喜欢热闹场面的可能觉得平淡","建议晚上 8 点后到场，技师上班更齐全"],
    conclusion: '凯旋桑拿是澳门市中心的隐藏宝石，适合喜欢安静环境和高品质服务的顾客。性价比高，私密性好，如果你想要避开人潮、在舒适环境中放松，凯旋无疑是最佳选择。',
  }
];

export function getVenueBySlug(slug: string): Venue | undefined {
  return venues.find((v) => v.slug === slug);
}

/** 暂停营业的场馆始终排到最后 */
function withSuspendedLast(list: Venue[]): Venue[] {
  return list.filter((v) => !v.suspended).concat(list.filter((v) => v.suspended));
}

export function getRankedVenues(): Venue[] {
  return withSuspendedLast([...venues].sort((a, b) => (a.ranking ?? 99) - (b.ranking ?? 99)));
}

export function getFeaturedVenues(): Venue[] {
  return withSuspendedLast(venues.filter((v) => v.tag === 'hot' || v.tag === 'new')).slice(0, 6);
}

/** 获取所有场馆（暂停营业排最后） */
export function getAllVenues(): Venue[] {
  return withSuspendedLast(venues);
}